# Generated by Django 5.0 on 2023-12-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_generatepasswordtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratePasswordToken',
        ),
    ]
